// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmZea3BOLI_eoGvdI-joCJL_Wjp55-0yE',
    appId: '1:516646458394:web:f9d5da4dd991e6949e2da3',
    messagingSenderId: '516646458394',
    projectId: 'tool-node-maria-final',
    authDomain: 'tool-node-maria-final.firebaseapp.com',
    storageBucket: 'tool-node-maria-final.firebasestorage.app',
    measurementId: 'G-BTT35TQ0LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASAWbFvcLY3Xc8piHy0msTdtZDg8kUsxU',
    appId: '1:516646458394:android:b182b24f1a7862c39e2da3',
    messagingSenderId: '516646458394',
    projectId: 'tool-node-maria-final',
    storageBucket: 'tool-node-maria-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXRTPt0zkBIDBLSMyt643QStmy0WR3MOc',
    appId: '1:516646458394:ios:352fd4f1d436de559e2da3',
    messagingSenderId: '516646458394',
    projectId: 'tool-node-maria-final',
    storageBucket: 'tool-node-maria-final.firebasestorage.app',
    iosBundleId: 'com.cusat.a2.toolNode',
  );
}
